//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCatalogue
{
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class ImageGallery
    {
        [Key]
        public int ImageId { get; set; }

        public int ImageSize { get; set; }

        public string FileName { get; set; }

        public byte[] ImageData { get; set; }

        public int ProductId { get; set; }

        [Required]
        public HttpPostedFileBase File { get; set; }
    }
}
