//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCatalogue
{
    using System.ComponentModel.DataAnnotations;

    public partial class Product
    {
        [Key]
        public int ProductsId { get; set; }

        public string ProductTitle { get; set; }

        public string ProductContent { get; set; }

        public decimal ProductPrice { get; set; }

        public int CategoryId { get; set; }
    }
}
